apiVersion: v1
kind: ConfigMap
metadata:
  name: runnable-config
  namespace: runnable
data:
  NODE_ENV: production
  PORT: "3000"
  TZ: Asia/Seoul
  BETTER_AUTH_URL: http://localhost:3000
  USE_DATABASE_MODE: POSTGRES
  ROUTE_MODE: NONE
