apiVersion: v1
kind: Secret
metadata:
  name: runnable-secret
  namespace: runnable
type: Opaque
stringData:
  POSTGRES_USER: root
  POSTGRES_PASSWORD: root1234
  POSTGRES_DB: runnable
  BETTER_AUTH_SECRET: minikube-dev-secret-key
  GITHUB_TOKEN: ""
  WEATHER_KOR: ""
  OPEN_DATA: ""
  TMAP_API: ""
