services:

  db:
    image: postgres:17-alpine
    container_name: runnable_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Seoul
    command: postgres -c 'timezone=Asia/Seoul'
    ports:
      - "127.0.0.1:6432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    image: runnable-app:latest   # 🔥 build 제거
    container_name: runnable_app
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      NODE_ENV: production
      PORT: 3000
      TZ: Asia/Seoul
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/public/uploads
    networks:
      - internal
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
    name: runnable_db_data

networks:
  internal:
    name: runnable_network
    driver: bridge
