# ============================================================
# 개발 환경용 Secret
# ============================================================
apiVersion: v1
kind: Secret
metadata:
  name: runnable-secret
  namespace: runnable
type: Opaque
stringData:
  POSTGRES_USER: root
  POSTGRES_PASSWORD: root1234
  POSTGRES_DB: runnable
  BETTER_AUTH_SECRET: runnable-better-auth-secret
  GITHUB_TOKEN: "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"
  WEATHER_KOR: "QC18uEOwSV"
  OPEN_DATA: "VCzeRv5K5pqKSztweNXA4lJt8uyxti3zL4LJr7h%2BKEULei9hs7ZRTRU0b5jSlTZQ5i3lycuEN7NS6uACbg4ZwA%3D%3D"
  TMAP_API: "wDMNwp1ocP7FykMk56cQc7U0c7VmhyJ128cyWIWA"
  WEBHOOK_SECRET: runnable-webhook-secret
  ADMIN_SEED_PASSWORD: admin1234
