FROM node:24-alpine

WORKDIR /workspace

COPY package.json pnpm-lock.yaml ./
COPY drizzle.config.ts ./
COPY server/database/ ./server/database/

RUN corepack enable && corepack prepare pnpm@latest --activate && \
    pnpm install --frozen-lockfile --ignore-scripts

CMD ["pnpm", "drizzle-kit", "push", "--force"]
